"""Suggested follow-up questions shown under an answer.

Static, reviewed wording only -- every suggestion is a question the knowledge base is built
to answer. Nothing is generated by a model, and none are offered for urgent or high-risk
conversations (the caller skips those).
"""

from __future__ import annotations

_BY_INTENT: dict[str, list[str]] = {
    "NUTRITION": [
        "Which foods are rich in iron?",
        "How much caffeine is okay?",
        "Which foods should I avoid?",
        "Which vitamins and supplements are recommended?",
    ],
    "EXERCISE": [
        "How much exercise should I do each week?",
        "Is yoga safe in pregnancy?",
        "Which exercises should I avoid?",
        "How do I do pelvic floor exercises?",
    ],
    "LIFESTYLE": [
        "What is the best sleeping position?",
        "How can I look after my mental health?",
        "Are vaccines recommended in pregnancy?",
    ],
    "ANTENATAL_CARE": [
        "What happens at antenatal appointments?",
        "Is there a free monthly check-up scheme in India?",
        "Which vaccines are recommended?",
    ],
    "AYURVEDA": [
        "What does Ayurveda advise for my stage?",
        "Is Ayurvedic advice backed by modern evidence?",
        "What should I eat according to Garbhini Paricharya?",
    ],
    "PREGNANCY_DEVELOPMENT": [
        "What should I expect at my next antenatal visit?",
        "What are the warning signs I should know?",
    ],
    "MEDICATION": [
        "Which vitamins and supplements are recommended?",
        "Which signs mean I should call my doctor?",
    ],
    "GENERAL": [
        "What should I eat at my stage?",
        "What exercise is safe for me?",
        "Which signs mean I should call my doctor?",
    ],
}

_BY_STAGE: dict[str, list[str]] = {
    "first_trimester": ["What helps with morning sickness?", "How much folic acid should I take?"],
    "second_trimester": ["How do I manage back pain?", "Is there a test for gestational diabetes?"],
    "third_trimester": ["What are the signs of labour?", "How do I prepare for breastfeeding?"],
}


def suggest_followups(intent: str, stage: str | None, asked: list[str] | None = None, limit: int = 3) -> list[str]:
    """Up to `limit` suggestions: one stage-specific first, then intent-specific, minus anything already asked."""
    asked_lower = {q.strip().lower() for q in (asked or [])}
    pool = (_BY_STAGE.get(stage or "", [])[:1]) + _BY_INTENT.get(intent, _BY_INTENT["GENERAL"]) + _BY_STAGE.get(stage or "", [])[1:]
    out: list[str] = []
    for question in pool:
        if question.lower() not in asked_lower and question not in out:
            out.append(question)
        if len(out) == limit:
            break
    return out
